# Generated by Django 6.0.2 on 2026-03-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguridadContactanos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=180)),
                ('email', models.EmailField(max_length=254)),
                ('compania_organizacion', models.CharField(blank=True, max_length=180)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('fecha_hora_insercion', models.DateTimeField(auto_now_add=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'db_table': 'seguridad_contactanos',
                'ordering': ['-fecha_hora_insercion'],
            },
        ),
    ]
