# Generated by Django 6.0.2 on 2026-03-02 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0004_catalogosentidadesfederativas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogosDelegaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('telefono', models.CharField(max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(help_text='Dirección completa para georreferenciación', max_length=255)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('horario', models.CharField(blank=True, help_text='Ej: Lun-Vie 8:00-17:00', max_length=100)),
                ('responsable', models.CharField(blank=True, max_length=150)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='delegaciones/')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delegaciones', to='anuncios.catalogosmunicipios')),
            ],
            options={
                'verbose_name': 'Delegación',
                'verbose_name_plural': 'Delegaciones',
                'db_table': 'catalogos_delegaciones',
                'ordering': ['nombre'],
            },
        ),
    ]
