# Generated by Django 6.0.2 on 2026-03-03 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0006_personaldireccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDepartamento',
            fields=[
                ('iddepartamento', models.AutoField(primary_key=True, serialize=False)),
                ('departamento', models.CharField(help_text='Nombre del departamento', max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional del departamento')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el departamento está vigente')),
                ('fecha_captura', models.DateTimeField(auto_now_add=True, help_text='Fecha cuando se registró el departamento')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha de la última modificación')),
                ('usuario_captura', models.CharField(blank=True, help_text='Usuario que capturó el registro', max_length=100)),
                ('usuario_modificacion', models.CharField(blank=True, help_text='Usuario que modificó el registro', max_length=100)),
                ('iddireccion', models.ForeignKey(help_text='Dirección a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='anuncios.personaldireccion')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'personal_departamento',
                'ordering': ['iddireccion', 'departamento'],
            },
        ),
    ]
