# Generated by Django 6.0.2 on 2026-03-03 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0007_personaldepartamento'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalempleados',
            name='iddepartamento',
            field=models.ForeignKey(blank=True, help_text='Departamento del empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='anuncios.personaldepartamento'),
        ),
        migrations.CreateModel(
            name='RecuperacionContrasena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('utilizado', models.BooleanField(default=False)),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recuperaciones', to='anuncios.personalempleados')),
            ],
            options={
                'verbose_name': 'Recuperación de Contraseña',
                'verbose_name_plural': 'Recuperaciones de Contraseña',
                'db_table': 'recuperacion_contrasena',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
