# Generated by Django 6.0.2 on 2026-03-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0008_personalempleados_recuperacioncontrasena'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalempleados',
            name='fotografia',
            field=models.ImageField(blank=True, help_text='Fotografía del empleado', null=True, upload_to='empleados/fotos/'),
        ),
    ]
