# Generated by Django 6.0.1 on 2026-03-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0021_configuracionsistema_tiempo_sesion_minutos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colacorreos',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Cola de Correos', 'verbose_name_plural': 'Cola de Correos'},
        ),
        migrations.RenameIndex(
            model_name='colacorreos',
            new_name='cola_correo_estado_454656_idx',
            old_name='cola_correos_estado_1234_idx',
        ),
        migrations.RenameIndex(
            model_name='colacorreos',
            new_name='cola_correo_email_d_9be3ce_idx',
            old_name='cola_correos_email_5678_idx',
        ),
        migrations.RenameIndex(
            model_name='patrimoniobienesdelinstituto',
            new_name='patrimonio__numero__130d48_idx',
            old_name='patri_bien_itavu_idx',
        ),
        migrations.RenameIndex(
            model_name='patrimoniobienesdelinstituto',
            new_name='patrimonio__numero__30c801_idx',
            old_name='patri_bien_gob_idx',
        ),
        migrations.RenameIndex(
            model_name='patrimoniobienesdelinstituto',
            new_name='patrimonio__activo_ccd21a_idx',
            old_name='patri_bien_activo_idx',
        ),
        migrations.AlterField(
            model_name='colacorreos',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado Correctamente'), ('error', 'Error')], default='pendiente', max_length=20),
        ),
        migrations.AlterModelTable(
            name='patrimoniobienesdelinstituto',
            table='patrimonio_bienes',
        ),
    ]
