# Generated by Django 6.0.1 on 2026-03-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0023_crear_tabla_resguardos'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrimonioresguardo',
            name='archivo_oficio',
            field=models.FileField(blank=True, help_text='PDF del oficio de asignación', null=True, upload_to='patrimonio/oficios/'),
        ),
        migrations.AddField(
            model_name='patrimonioresguardo',
            name='fecha_oficio',
            field=models.DateField(blank=True, help_text='Fecha del oficio de asignación', null=True),
        ),
        migrations.AddField(
            model_name='patrimonioresguardo',
            name='numero_oficio',
            field=models.CharField(blank=True, help_text='Número de oficio de asignación', max_length=100),
        ),
    ]
