# Generated by Django 6.0.1 on 2026-03-06 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0025_patrimoniobienesdelinstituto_archivo_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatrimonioEntregaDepartamento',
            fields=[
                ('identrega', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrega', models.DateField(help_text='Fecha de entrega-recepción')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones generales de la entrega')),
                ('total_bienes', models.PositiveIntegerField(default=0, help_text='Cantidad de bienes transferidos')),
                ('usuario_registro', models.CharField(blank=True, help_text='Usuario que registró la entrega', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(help_text='Departamento al que corresponde la entrega', on_delete=django.db.models.deletion.PROTECT, related_name='entregas_departamento', to='anuncios.personaldepartamento')),
                ('empleado_entrante', models.ForeignKey(help_text='Empleado que recibe los bienes', on_delete=django.db.models.deletion.PROTECT, related_name='entregas_departamento_entrante', to=settings.AUTH_USER_MODEL)),
                ('empleado_saliente', models.ForeignKey(help_text='Empleado que entrega los bienes', on_delete=django.db.models.deletion.PROTECT, related_name='entregas_departamento_saliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrega de Departamento',
                'verbose_name_plural': 'Entregas de Departamento',
                'db_table': 'patrimonio_entrega_departamento',
                'ordering': ['-fecha_entrega', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PatrimonioEntregaDepartamentoDetalle',
            fields=[
                ('iddetalle', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_transferencia', models.DateField(help_text='Fecha de transferencia del bien')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones del bien transferido')),
                ('bien', models.ForeignKey(help_text='Bien transferido', on_delete=django.db.models.deletion.PROTECT, related_name='entregas_departamento', to='anuncios.patrimoniobienesdelinstituto')),
                ('entrega', models.ForeignKey(help_text='Entrega de departamento', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='anuncios.patrimonioentregadepartamento')),
                ('resguardo_anterior', models.ForeignKey(blank=True, help_text='Resguardo que se cierra', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_entrega_anterior', to='anuncios.patrimonioresguardo')),
                ('resguardo_nuevo', models.ForeignKey(blank=True, help_text='Resguardo creado para el empleado entrante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_entrega_nuevo', to='anuncios.patrimonioresguardo')),
            ],
            options={
                'verbose_name': 'Detalle de Entrega de Departamento',
                'verbose_name_plural': 'Detalles de Entrega de Departamento',
                'db_table': 'patrimonio_entrega_departamento_detalle',
                'ordering': ['iddetalle'],
            },
        ),
        migrations.AddIndex(
            model_name='patrimonioentregadepartamento',
            index=models.Index(fields=['departamento', 'fecha_entrega'], name='patrimonio__departa_b71d3b_idx'),
        ),
        migrations.AddIndex(
            model_name='patrimonioentregadepartamento',
            index=models.Index(fields=['empleado_saliente'], name='patrimonio__emplead_40f271_idx'),
        ),
        migrations.AddIndex(
            model_name='patrimonioentregadepartamento',
            index=models.Index(fields=['empleado_entrante'], name='patrimonio__emplead_d35d37_idx'),
        ),
        migrations.AddConstraint(
            model_name='patrimonioentregadepartamentodetalle',
            constraint=models.UniqueConstraint(fields=('entrega', 'bien'), name='unique_bien_por_entrega_departamento'),
        ),
    ]
