# Generated by Django 6.0.2 on 2026-03-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0027_alter_personaldepartamento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimonioproveedor',
            name='correo',
            field=models.EmailField(blank=True, help_text='Correo del proveedor', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='patrimonioproveedor',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción adicional', null=True),
        ),
        migrations.AlterField(
            model_name='patrimonioproveedor',
            name='domicilio',
            field=models.TextField(blank=True, help_text='Domicilio del proveedor', null=True),
        ),
        migrations.AlterField(
            model_name='patrimonioproveedor',
            name='persona_contacto',
            field=models.CharField(blank=True, help_text='Persona de contacto', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patrimonioproveedor',
            name='rfc',
            field=models.CharField(blank=True, help_text='RFC del proveedor', max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patrimonioproveedor',
            name='telefono',
            field=models.CharField(blank=True, help_text='Teléfono del proveedor', max_length=20, null=True),
        ),
    ]
