# Generated by Django 6.0.1 on 2026-03-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0030_catalogosmarcas_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogosmarcas',
            name='categoria',
        ),
    ]
