# Generated by Django 6.0.1 on 2026-03-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0031_remove_catalogosmarcas_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatrimonioEstatusArticulo',
            fields=[
                ('idestatusarticulo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(help_text='Descripción del estatus', max_length=200, unique=True)),
                ('idestatus', models.IntegerField(choices=[(0, 'Activo'), (1, 'Eliminado')], default=0, help_text='Estado del estatus (0=activo, 1=eliminado)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estatus del Artículo',
                'verbose_name_plural': 'Estatus de Artículos',
                'db_table': 'patrimonio_estatusdelarticulo',
                'ordering': ['descripcion'],
            },
        ),
    ]
