# Generated by Django 6.0.1 on 2026-03-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0032_patrimonioestatusarticulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatrimonioEstatusDelRegistro',
            fields=[
                ('idestatus', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(help_text='Descripción del estatus del registro', max_length=200, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estatus del Registro',
                'verbose_name_plural': 'Estatus de Registros',
                'db_table': 'patrimonio_estatusdelregistro',
                'ordering': ['idestatus'],
            },
        ),
    ]
