# Generated by Django 6.0.1 on 2026-03-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0035_remove_patrimoniobienesdelinstituto_patrimonio__activo_ccd21a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrimoniobienesdelinstituto',
            name='baja_numero_oficio',
            field=models.CharField(blank=True, help_text='Número del oficio de baja', max_length=100),
        ),
    ]
