# Generated by Django 6.0.1 on 2026-03-11 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0037_patrimoniobienesdelinstituto_numinv_monitor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogosSexo',
            fields=[
                ('idsexo', models.AutoField(primary_key=True, serialize=False)),
                ('sexo', models.CharField(help_text='Descripción del sexo', max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True, help_text='¿El catálogo está activo?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sexo',
                'verbose_name_plural': 'Sexos',
                'db_table': 'catalogos_sexo',
                'ordering': ['idsexo'],
            },
        ),
        migrations.CreateModel(
            name='FerCatSubsidio',
            fields=[
                ('fer_idcon', models.AutoField(primary_key=True, serialize=False)),
                ('fer_descripcion', models.CharField(help_text='Descripción del concepto de subsidio', max_length=255)),
                ('activo', models.BooleanField(default=True, help_text='¿El concepto está activo?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Concepto de Subsidio FER',
                'verbose_name_plural': 'Conceptos de Subsidio FER',
                'db_table': 'fer_cat_subsidio',
                'ordering': ['fer_idcon'],
            },
        ),
        migrations.CreateModel(
            name='FerFondos',
            fields=[
                ('idfondo', models.AutoField(primary_key=True, serialize=False)),
                ('fondo', models.BigIntegerField(help_text='Cantidad del fondo disponible')),
                ('ejercicio', models.IntegerField(help_text='Año fiscal', unique=True)),
                ('fechainicio', models.DateField(help_text='Fecha de inicio del fondo')),
                ('fechafin', models.DateField(help_text='Fecha de fin del fondo')),
                ('sustento', models.TextField(help_text='Sustento o referencia legal del fondo')),
                ('activo', models.BooleanField(default=True, help_text='¿El fondo está activo?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fondo FER',
                'verbose_name_plural': 'Fondos FER',
                'db_table': 'fer_fondos',
                'ordering': ['-ejercicio'],
            },
        ),
        migrations.CreateModel(
            name='FerInformacion',
            fields=[
                ('nfer_id', models.AutoField(primary_key=True, serialize=False)),
                ('ejercicio', models.IntegerField(help_text='Año fiscal del registro')),
                ('numcertificado', models.IntegerField(blank=True, help_text='Número de certificado', null=True)),
                ('contrato', models.CharField(help_text='Número de contrato', max_length=255)),
                ('nombre', models.CharField(help_text='Nombre del beneficiario', max_length=255)),
                ('curp', models.CharField(help_text='CURP del beneficiario', max_length=18)),
                ('descripcion', models.TextField(help_text='Descripción del concepto')),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad del subsidio', max_digits=15)),
                ('nacimiento', models.DateField(help_text='Fecha de nacimiento')),
                ('domicilio', models.TextField(help_text='Domicilio del beneficiario')),
                ('telefono', models.CharField(help_text='Teléfono del beneficiario', max_length=20)),
                ('celular', models.CharField(help_text='Celular del beneficiario', max_length=20)),
                ('autorizo', models.CharField(help_text='Persona que autorizó el subsidio', max_length=255)),
                ('autorizo_fecha', models.DateField(help_text='Fecha cuando se autorizó')),
                ('autorizo_hora', models.TimeField(help_text='Hora cuando se autorizó')),
                ('estado', models.IntegerField(choices=[(0, 'Activo'), (1, 'Inactivo')], default=0, help_text='Estado del registro (0=Activo, 1=Inactivo)')),
                ('parrafo_opcional', models.TextField(blank=True, help_text='Párrafo adicional opcional')),
                ('idempmodifica', models.CharField(blank=True, help_text='ID del empleado que modificó', max_length=255, null=True)),
                ('fechaultimamod', models.DateField(blank=True, help_text='Fecha última modificación', null=True)),
                ('archivo_sustento', models.FileField(blank=True, help_text='Archivo que sustenta la captura', null=True, upload_to='fer/sustentos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion_sistema', models.DateTimeField(auto_now=True)),
                ('idmunicipio', models.ForeignKey(help_text='Municipio del beneficiario', on_delete=django.db.models.deletion.PROTECT, related_name='fer_informaciones', to='anuncios.catalogosmunicipios')),
                ('nfer_concepto', models.ForeignKey(help_text='Concepto de subsidio', on_delete=django.db.models.deletion.PROTECT, related_name='informaciones', to='anuncios.fercatsubsidio')),
                ('sexo', models.ForeignKey(help_text='Sexo del beneficiario', on_delete=django.db.models.deletion.PROTECT, related_name='fer_informaciones', to='anuncios.catalogossexo')),
            ],
            options={
                'verbose_name': 'Información FER',
                'verbose_name_plural': 'Información FER',
                'db_table': 'fer_informacion',
                'ordering': ['-ejercicio', '-numcertificado'],
                'indexes': [models.Index(fields=['ejercicio', 'estado'], name='fer_informa_ejercic_408d7c_idx'), models.Index(fields=['curp'], name='fer_informa_curp_a9e08d_idx'), models.Index(fields=['estado'], name='fer_informa_estado_7e8ec6_idx')],
                'unique_together': {('nfer_id', 'ejercicio')},
            },
        ),
    ]
