# Generated by Django 6.0.1 on 2026-03-11 18:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0037_patrimoniobienesdelinstituto_numinv_monitor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketServicio',
            fields=[
                ('id_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('folio', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('asunto', models.CharField(help_text='Título breve del ticket', max_length=255)),
                ('descripcion', models.TextField(help_text='Descripción detallada del ticket')),
                ('categoria', models.CharField(choices=[('solicitud', 'Solicitud'), ('informacion', 'Información'), ('soporte', 'Soporte Técnico'), ('tramite', 'Trámite'), ('otro', 'Otro')], default='solicitud', max_length=30)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En Proceso'), ('en_espera', 'En Espera'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='abierto', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha límite esperada', null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('emisor', models.ForeignKey(help_text='Quien crea el ticket', on_delete=django.db.models.deletion.PROTECT, related_name='tickets_enviados', to=settings.AUTH_USER_MODEL)),
                ('receptor', models.ForeignKey(help_text='A quien va dirigido el ticket', on_delete=django.db.models.deletion.PROTECT, related_name='tickets_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket de Servicio',
                'verbose_name_plural': 'Tickets de Servicio',
                'db_table': 'tickets_servicio',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TicketServicioArchivo',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='tickets/adjuntos/%Y/%m/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('tamanio', models.PositiveIntegerField(default=0, help_text='Tamaño en bytes')),
                ('tipo_mime', models.CharField(blank=True, max_length=100)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_tickets', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='anuncios.ticketservicio')),
            ],
            options={
                'verbose_name': 'Archivo de Ticket',
                'verbose_name_plural': 'Archivos de Tickets',
                'db_table': 'tickets_servicio_archivo',
                'ordering': ['fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='TicketServicioComentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('es_nota_interna', models.BooleanField(default=False, help_text='Solo visible para el emisor del ticket')),
                ('cambio_estado', models.CharField(blank=True, help_text='Estado anterior si hubo cambio', max_length=15)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_tickets', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='anuncios.ticketservicio')),
            ],
            options={
                'verbose_name': 'Comentario de Ticket',
                'verbose_name_plural': 'Comentarios de Tickets',
                'db_table': 'tickets_servicio_comentario',
                'ordering': ['fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='ticketservicio',
            index=models.Index(fields=['estado', 'prioridad'], name='tickets_ser_estado_7f8466_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketservicio',
            index=models.Index(fields=['emisor', 'receptor'], name='tickets_ser_emisor__83a222_idx'),
        ),
    ]
