# Generated by Django 6.0.1 on 2026-03-11 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0038_catalogossexo_fercatsubsidio_ferfondos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferinformacion',
            name='autorizo',
            field=models.CharField(blank=True, help_text='Persona que autorizó el subsidio', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ferinformacion',
            name='autorizo_fecha',
            field=models.DateField(blank=True, help_text='Fecha cuando se autorizó', null=True),
        ),
        migrations.AlterField(
            model_name='ferinformacion',
            name='autorizo_hora',
            field=models.TimeField(blank=True, help_text='Hora cuando se autorizó', null=True),
        ),
        migrations.AlterField(
            model_name='ferinformacion',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad del subsidio', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='ferinformacion',
            name='celular',
            field=models.CharField(blank=True, help_text='Celular del beneficiario', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ferinformacion',
            name='contrato',
            field=models.CharField(blank=True, help_text='Número de contrato', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ferinformacion',
            name='curp',
            field=models.CharField(blank=True, help_text='CURP del beneficiario', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='ferinformacion',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción del concepto', null=True),
        ),
        migrations.AlterField(
            model_name='ferinformacion',
            name='domicilio',
            field=models.TextField(blank=True, help_text='Domicilio del beneficiario', null=True),
        ),
        migrations.AlterField(
            model_name='ferinformacion',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(0, 'Activo'), (1, 'Inactivo')], default=0, help_text='Estado del registro (0=Activo, 1=Inactivo)', null=True),
        ),
        migrations.AlterField(
            model_name='ferinformacion',
            name='idmunicipio',
            field=models.ForeignKey(blank=True, help_text='Municipio del beneficiario', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fer_informaciones', to='anuncios.catalogosmunicipios'),
        ),
        migrations.AlterField(
            model_name='ferinformacion',
            name='nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento', null=True),
        ),
        migrations.AlterField(
            model_name='ferinformacion',
            name='nfer_concepto',
            field=models.ForeignKey(blank=True, help_text='Concepto de subsidio', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='informaciones', to='anuncios.fercatsubsidio'),
        ),
        migrations.AlterField(
            model_name='ferinformacion',
            name='nombre',
            field=models.CharField(blank=True, help_text='Nombre del beneficiario', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ferinformacion',
            name='parrafo_opcional',
            field=models.TextField(blank=True, help_text='Párrafo adicional opcional', null=True),
        ),
        migrations.AlterField(
            model_name='ferinformacion',
            name='sexo',
            field=models.ForeignKey(blank=True, help_text='Sexo del beneficiario', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fer_informaciones', to='anuncios.catalogossexo'),
        ),
        migrations.AlterField(
            model_name='ferinformacion',
            name='telefono',
            field=models.CharField(blank=True, help_text='Teléfono del beneficiario', max_length=20, null=True),
        ),
    ]
