# Generated by Django 6.0.1 on 2026-03-11 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0038_transparenciago'),
        ('anuncios', '0039_ticket_departamento_destino'),
    ]

    operations = [
    ]
