# Generated by Django 6.0.1 on 2026-03-18 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0040_catalogos_administraciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ferinformacion',
            name='idmunicipio',
        ),
        migrations.RemoveField(
            model_name='ferinformacion',
            name='nacimiento',
        ),
        migrations.RemoveField(
            model_name='ferinformacion',
            name='sexo',
        ),
        migrations.AddField(
            model_name='ferinformacion',
            name='fechanacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento', null=True),
        ),
        migrations.AddField(
            model_name='ferinformacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='ferinformacion',
            name='id_municipio',
            field=models.ForeignKey(blank=True, db_column='id_municipio', help_text='Municipio del beneficiario', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fer_informaciones', to='anuncios.catalogosmunicipios'),
        ),
        migrations.AddField(
            model_name='ferinformacion',
            name='id_sexo',
            field=models.ForeignKey(blank=True, db_column='id_sexo', help_text='Sexo del beneficiario', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fer_informaciones', to='anuncios.catalogossexo'),
        ),
        migrations.AlterField(
            model_name='ferinformacion',
            name='archivo_sustento',
            field=models.CharField(blank=True, help_text='Archivo que sustenta la captura', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ferinformacion',
            name='contrato',
            field=models.CharField(blank=True, help_text='Número de contrato', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ferinformacion',
            name='fecha_creacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ferinformacion',
            name='fecha_modificacion_sistema',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ferinformacion',
            name='idempmodifica',
            field=models.IntegerField(blank=True, help_text='ID del empleado que modificó', null=True),
        ),
        migrations.AlterField(
            model_name='ferinformacion',
            name='nfer_concepto',
            field=models.ForeignKey(blank=True, db_column='nfer_concepto_id', help_text='Concepto de subsidio', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='informaciones', to='anuncios.fercatsubsidio'),
        ),
        migrations.AlterField(
            model_name='ferinformacion',
            name='nfer_id',
            field=models.IntegerField(help_text='ID del registro FER'),
        ),
    ]
