# Generated by Django 6.0.1 on 2026-03-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0040_merge_20260311_1511'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ticketservicio',
            new_name='tickets_ser_emisor__ed0415_idx',
            old_name='tickets_ser_emisor__dep_idx',
        ),
        migrations.AlterField(
            model_name='transparenciago',
            name='id_file',
            field=models.AutoField(db_column='IdFile', primary_key=True, serialize=False),
        ),
    ]
