# Generated by Django 6.0.1 on 2026-03-12 14:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0041_rename_tickets_ser_emisor__dep_idx_tickets_ser_emisor__ed0415_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='departamento_soporte_mantenimiento',
            field=models.ForeignKey(blank=True, help_text='Departamento que atenderá los tickets de Servicio de Mantenimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_soporte_mantenimiento', to='anuncios.personaldepartamento'),
        ),
        migrations.CreateModel(
            name='TicketMantenimiento',
            fields=[
                ('id_ticket_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('folio', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('asunto', models.CharField(help_text='Título breve de la incidencia', max_length=255)),
                ('descripcion', models.TextField(help_text='Descripción del problema reportado')),
                ('tipo_equipo', models.CharField(choices=[('desktop', 'Computadora de escritorio'), ('laptop', 'Laptop'), ('impresora', 'Impresora'), ('scanner', 'Escáner'), ('red', 'Red / Internet'), ('periferico', 'Periférico'), ('otro', 'Otro')], default='desktop', max_length=20)),
                ('equipo', models.CharField(blank=True, help_text='Nombre o referencia del equipo', max_length=150)),
                ('numero_inventario', models.CharField(blank=True, help_text='Número de inventario o serie', max_length=100)),
                ('ubicacion', models.CharField(blank=True, help_text='Ubicación exacta del equipo o del solicitante', max_length=255)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('critica', 'Crítica')], default='normal', max_length=10)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('asignado', 'Asignado'), ('en_revision', 'En revisión'), ('en_reparacion', 'En reparación'), ('espera_refaccion', 'En espera de refacción'), ('resuelto', 'Resuelto'), ('entregado', 'Entregado'), ('cerrado', 'Cerrado')], default='abierto', max_length=20)),
                ('solicita_formateo', models.BooleanField(default=False)),
                ('equipo_retirado', models.BooleanField(default=False)),
                ('trabajo_realizado', models.TextField(blank=True)),
                ('piezas_instaladas', models.TextField(blank=True)),
                ('fecha_retiro_equipo', models.DateTimeField(blank=True, null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega_equipo', models.DateTimeField(blank=True, null=True)),
                ('solucion_confirmada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('atendido_por', models.ForeignKey(blank=True, help_text='Empleado del área de soporte que atiende el ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_mantenimiento_atendidos', to=settings.AUTH_USER_MODEL)),
                ('departamento_solicitante', models.ForeignKey(blank=True, help_text='Departamento del empleado solicitante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_mantenimiento_solicitados', to='anuncios.personaldepartamento')),
                ('departamento_soporte', models.ForeignKey(help_text='Departamento responsable de la atención', on_delete=django.db.models.deletion.PROTECT, related_name='tickets_mantenimiento_recibidos', to='anuncios.personaldepartamento')),
                ('solicitante', models.ForeignKey(help_text='Empleado que reporta la incidencia', on_delete=django.db.models.deletion.PROTECT, related_name='tickets_mantenimiento_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket de Mantenimiento',
                'verbose_name_plural': 'Tickets de Mantenimiento',
                'db_table': 'tickets_mantenimiento',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TicketMantenimientoArchivo',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='mantenimiento/adjuntos/%Y/%m/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('tamanio', models.PositiveIntegerField(default=0)),
                ('tipo_mime', models.CharField(blank=True, max_length=100)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_tickets_mantenimiento', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='anuncios.ticketmantenimiento')),
            ],
            options={
                'verbose_name': 'Archivo de Ticket de Mantenimiento',
                'verbose_name_plural': 'Archivos de Tickets de Mantenimiento',
                'db_table': 'tickets_mantenimiento_archivo',
                'ordering': ['fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='TicketMantenimientoSeguimiento',
            fields=[
                ('id_seguimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('comentario', 'Comentario'), ('estado', 'Cambio de estado'), ('intervencion', 'Intervención técnica'), ('notificacion', 'Notificación')], default='comentario', max_length=20)),
                ('mensaje', models.TextField()),
                ('trabajo_realizado', models.TextField(blank=True)),
                ('piezas_instaladas', models.TextField(blank=True)),
                ('cambio_estado', models.CharField(blank=True, max_length=20)),
                ('notificar_solicitante', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_tickets_mantenimiento', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='anuncios.ticketmantenimiento')),
            ],
            options={
                'verbose_name': 'Seguimiento de Ticket de Mantenimiento',
                'verbose_name_plural': 'Seguimientos de Tickets de Mantenimiento',
                'db_table': 'tickets_mantenimiento_seguimiento',
                'ordering': ['fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='ticketmantenimiento',
            index=models.Index(fields=['estado', 'prioridad'], name='tickets_man_estado_5f66f5_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmantenimiento',
            index=models.Index(fields=['solicitante', 'departamento_soporte'], name='tickets_man_solicit_45fb5d_idx'),
        ),
    ]
