# Generated by Django 6.0.1 on 2026-03-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0042_configuracionsistema_departamento_soporte_mantenimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmantenimiento',
            name='fecha_limite_sla',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketmantenimiento',
            name='sla_horas_objetivo',
            field=models.PositiveIntegerField(default=48),
        ),
    ]
