# Generated by Django 6.0.1 on 2026-03-26 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0044_vehiculofoto_orden'),
        ('anuncios', '0045_backfill_sla_tickets_mantenimiento'),
    ]

    operations = [
    ]
