# Generated by Django 6.0.1 on 2026-03-27 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0046_merge_20260326_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculofoto',
            options={'ordering': ['-es_principal', 'orden', '-fecha_captura'], 'verbose_name': 'Foto de Vehiculo', 'verbose_name_plural': 'Fotos de Vehiculos'},
        ),
    ]
