# Generated by Django 6.0.1 on 2026-03-30 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0041_remove_ferinformacion_idmunicipio_and_more'),
        ('anuncios', '0046_merge_20260326_1228'),
    ]

    operations = [
    ]
