# Generated by Django 6.0.2 on 2026-04-06 16:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from decimal import Decimal
from django.db import migrations, models


def cargar_catalogo_inicial_requisiciones(apps, schema_editor):
    RequisicionesClasificacion = apps.get_model('anuncios', 'RequisicionesClasificacion')
    RequisicionesCatalogoArticulos = apps.get_model('anuncios', 'RequisicionesCatalogoArticulos')

    clasificaciones = {
        'Papelería': 'Artículos de oficina y consumibles de uso diario.',
        'Material de Limpieza': 'Productos de limpieza y mantenimiento de áreas.',
        'Electrónica': 'Equipo periférico, accesorios y componentes electrónicos.',
    }

    clasificaciones_creadas = {}
    for nombre, descripcion in clasificaciones.items():
        clasificacion, _ = RequisicionesClasificacion.objects.get_or_create(
            nombre=nombre,
            defaults={
                'descripcion': descripcion,
                'activo': True,
            },
        )
        clasificaciones_creadas[nombre] = clasificacion

    articulos = [
        ('Resma carta blanca', 'Papelería', 'Resma de papel tamaño carta de 500 hojas.', 'paquete', 40, Decimal('118.50')),
        ('Bolígrafo tinta azul', 'Papelería', 'Caja con bolígrafos de tinta azul punta media.', 'caja', 25, Decimal('95.00')),
        ('Folder tamaño oficio', 'Papelería', 'Paquete de folders color beige tamaño oficio.', 'paquete', 30, Decimal('84.90')),
        ('Notas adhesivas', 'Papelería', 'Paquete de notas adhesivas de colores surtidos.', 'paquete', 18, Decimal('62.00')),
        ('Detergente multiusos', 'Material de Limpieza', 'Limpiador multiusos para superficies y mobiliario.', 'caja', 12, Decimal('310.00')),
        ('Papel higiénico institucional', 'Material de Limpieza', 'Caja con rollos institucionales para sanitarios.', 'caja', 20, Decimal('428.75')),
        ('Jabón para manos', 'Material de Limpieza', 'Caja con botellas rellenables de jabón líquido.', 'caja', 16, Decimal('276.40')),
        ('Mouse óptico USB', 'Electrónica', 'Mouse alámbrico ergonómico con conexión USB.', 'pieza', 14, Decimal('189.00')),
        ('Teclado USB', 'Electrónica', 'Teclado alámbrico estándar para equipo de cómputo.', 'pieza', 10, Decimal('245.00')),
        ('Memoria USB 64 GB', 'Electrónica', 'Memoria USB para respaldo de información institucional.', 'pieza', 22, Decimal('215.50')),
    ]

    for nombre, clasificacion_nombre, descripcion, unidad, stock, precio in articulos:
        RequisicionesCatalogoArticulos.objects.get_or_create(
            nombre=nombre,
            defaults={
                'clasificacion': clasificaciones_creadas[clasificacion_nombre],
                'descripcion': descripcion,
                'unidad_medida': unidad,
                'stock_actual': stock,
                'precio_referencia': precio,
                'activo': True,
                'usuario_captura': 'migracion_0048',
                'usuario_modificacion': 'migracion_0048',
            },
        )


def revertir_catalogo_inicial_requisiciones(apps, schema_editor):
    RequisicionesClasificacion = apps.get_model('anuncios', 'RequisicionesClasificacion')
    RequisicionesCatalogoArticulos = apps.get_model('anuncios', 'RequisicionesCatalogoArticulos')

    nombres_articulos = [
        'Resma carta blanca',
        'Bolígrafo tinta azul',
        'Folder tamaño oficio',
        'Notas adhesivas',
        'Detergente multiusos',
        'Papel higiénico institucional',
        'Jabón para manos',
        'Mouse óptico USB',
        'Teclado USB',
        'Memoria USB 64 GB',
    ]
    RequisicionesCatalogoArticulos.objects.filter(nombre__in=nombres_articulos).delete()
    RequisicionesClasificacion.objects.filter(nombre__in=['Papelería', 'Material de Limpieza', 'Electrónica']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0047_alter_vehiculofoto_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisicionesClasificacion',
            fields=[
                ('id_clasificacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_captura', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clasificación de Artículo',
                'verbose_name_plural': 'Clasificaciones de Artículos',
                'db_table': 'requisiciones_clasificaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE configuracion_sistema
                    ADD COLUMN IF NOT EXISTS departamento_compras_requisiciones_id integer NULL;

                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM pg_constraint
                            WHERE conname = 'config_sistema_depto_compras_fk'
                        ) THEN
                            ALTER TABLE configuracion_sistema
                            ADD CONSTRAINT config_sistema_depto_compras_fk
                            FOREIGN KEY (departamento_compras_requisiciones_id)
                            REFERENCES personal_departamento(iddepartamento)
                            DEFERRABLE INITIALLY DEFERRED;
                        END IF;
                    END $$;

                    CREATE INDEX IF NOT EXISTS config_sistema_depto_compras_idx
                    ON configuracion_sistema (departamento_compras_requisiciones_id);
                    """,
                    reverse_sql="""
                    DROP INDEX IF EXISTS config_sistema_depto_compras_idx;
                    ALTER TABLE configuracion_sistema
                    DROP CONSTRAINT IF EXISTS config_sistema_depto_compras_fk;
                    ALTER TABLE configuracion_sistema
                    DROP COLUMN IF EXISTS departamento_compras_requisiciones_id;
                    """,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='configuracionsistema',
                    name='departamento_compras_requisiciones',
                    field=models.ForeignKey(blank=True, help_text='Departamento que atenderá Requisiciones y el módulo de Compras', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_compras_requisiciones', to='anuncios.personaldepartamento'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='RequisicionesCatalogoArticulos',
            fields=[
                ('id_articulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('unidad_medida', models.CharField(choices=[('pieza', 'Pieza'), ('caja', 'Caja'), ('paquete', 'Paquete')], default='pieza', max_length=20)),
                ('stock_actual', models.PositiveIntegerField(default=0)),
                ('precio_referencia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='requisiciones/articulos/')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_captura', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_captura', models.CharField(blank=True, max_length=100)),
                ('usuario_modificacion', models.CharField(blank=True, max_length=100)),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articulos', to='anuncios.requisicionesclasificacion')),
            ],
            options={
                'verbose_name': 'Artículo de Requisiciones',
                'verbose_name_plural': 'Catálogo de Artículos para Requisiciones',
                'db_table': 'requisiciones_catalogodearticulos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RequisicionesSolicitud',
            fields=[
                ('id_requisicion', models.AutoField(primary_key=True, serialize=False)),
                ('folio', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('estatus', models.CharField(choices=[('pendiente', 'Pendiente de atender'), ('en_proceso', 'En proceso'), ('para_entrega', 'Para entrega'), ('no_autorizado', 'No autorizado'), ('entregado', 'Entregado')], default='pendiente', max_length=20)),
                ('comentarios_compra', models.TextField(blank=True)),
                ('no_autorizado_motivo', models.TextField(blank=True)),
                ('fecha_toma', models.DateTimeField(blank=True, null=True)),
                ('fecha_para_entrega', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('atendido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisiciones_atendidas', to=settings.AUTH_USER_MODEL)),
                ('departamento_atencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisiciones_recibidas', to='anuncios.personaldepartamento')),
                ('departamento_solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisiciones_solicitadas', to='anuncios.personaldepartamento')),
                ('recibido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisiciones_recibidas_empleado', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisiciones_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requisición',
                'verbose_name_plural': 'Requisiciones',
                'db_table': 'requisiciones_solicitudes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RequisicionesSeguimiento',
            fields=[
                ('id_seguimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('estado', 'Cambio de estado'), ('comentario', 'Comentario'), ('documento', 'Documento'), ('entrega', 'Entrega')], default='comentario', max_length=20)),
                ('mensaje', models.TextField()),
                ('estatus_anterior', models.CharField(blank=True, max_length=20)),
                ('estatus_nuevo', models.CharField(blank=True, max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_requisiciones', to=settings.AUTH_USER_MODEL)),
                ('requisicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='anuncios.requisicionessolicitud')),
            ],
            options={
                'verbose_name': 'Seguimiento de Requisición',
                'verbose_name_plural': 'Seguimientos de Requisiciones',
                'db_table': 'requisiciones_seguimiento',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='RequisicionesSolicitudDetalle',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.TextField(help_text='Justificación, descripción o motivo de solicitud')),
                ('cantidad_solicitada', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unidad_medida', models.CharField(choices=[('pieza', 'Pieza'), ('caja', 'Caja'), ('paquete', 'Paquete')], default='pieza', max_length=20)),
                ('cantidad_autorizada', models.PositiveIntegerField(default=0)),
                ('cantidad_entregada', models.PositiveIntegerField(default=0)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estatus_detalle', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('no_autorizado', 'No autorizado'), ('para_entrega', 'Para entrega'), ('entregado', 'Entregado')], default='pendiente', max_length=20)),
                ('observaciones_compra', models.TextField(blank=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_requisicion', to='anuncios.requisicionescatalogoarticulos')),
                ('requisicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='anuncios.requisicionessolicitud')),
            ],
            options={
                'verbose_name': 'Detalle de Requisición',
                'verbose_name_plural': 'Detalles de Requisición',
                'db_table': 'requisiciones_detalle',
                'ordering': ['id_detalle'],
            },
        ),
        migrations.CreateModel(
            name='RequisicionesDocumento',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('cotizacion', 'Cotización'), ('factura', 'Factura')], max_length=20)),
                ('archivo', models.FileField(upload_to='requisiciones/documentos/%Y/%m/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_requisiciones_subidos', to=settings.AUTH_USER_MODEL)),
                ('requisicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='anuncios.requisicionessolicitud')),
                ('detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='anuncios.requisicionessolicituddetalle')),
            ],
            options={
                'verbose_name': 'Documento de Requisición',
                'verbose_name_plural': 'Documentos de Requisiciones',
                'db_table': 'requisiciones_documentos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.AddIndex(
            model_name='requisicionescatalogoarticulos',
            index=models.Index(fields=['activo', 'nombre'], name='requisicion_activo_65949a_idx'),
        ),
        migrations.AddIndex(
            model_name='requisicionessolicitud',
            index=models.Index(fields=['estatus', 'fecha_creacion'], name='requisicion_estatus_b605b5_idx'),
        ),
        migrations.AddIndex(
            model_name='requisicionessolicitud',
            index=models.Index(fields=['departamento_solicitante', 'estatus'], name='requisicion_departa_d09eeb_idx'),
        ),
        migrations.RunPython(cargar_catalogo_inicial_requisiciones, revertir_catalogo_inicial_requisiciones),
    ]
