# Generated by Django 6.0.2 on 2026-03-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0039_alter_ferinformacion_autorizo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogosAdministraciones',
            fields=[
                ('idadministracion', models.AutoField(primary_key=True, serialize=False)),
                ('fechainicio', models.DateField(help_text='Fecha de inicio de la administración')),
                ('fechatermino', models.DateField(help_text='Fecha de término de la administración')),
                ('fecha_creacion', models.DateTimeField(help_text='Fecha de creación del registro')),
                ('id_empleado', models.IntegerField(help_text='ID del empleado responsable')),
                ('gobernador', models.CharField(help_text='Nombre del gobernador', max_length=255)),
            ],
            options={
                'db_table': 'catalogos_administraciones',
                'verbose_name': 'Administración',
                'verbose_name_plural': 'Administraciones',
                'ordering': ['-fechainicio'],
            },
        ),
    ]
