# Generated by Django 6.0.2 on 2026-04-08 21:33

import django.core.validators
import django.db.models.deletion
import portal.models
from django.conf import settings
from django.db import migrations, models


def cargar_zonas_viaticos(apps, schema_editor):
    ViaticosZonaTarifa = apps.get_model('anuncios', 'ViaticosZonaTarifa')
    zonas = [
        ('norte', 'Zona Norte', '1850.00', '475.00', '4.2500'),
        ('centro', 'Zona Centro', '1450.00', '425.00', '3.9500'),
        ('sur', 'Zona Sur', '1700.00', '460.00', '4.1000'),
    ]

    for clave, nombre, hospedaje, alimentacion, combustible in zonas:
        ViaticosZonaTarifa.objects.update_or_create(
            clave=clave,
            defaults={
                'nombre': nombre,
                'hospedaje_noche': hospedaje,
                'alimentacion_diaria': alimentacion,
                'combustible_km': combustible,
                'activo': True,
            }
        )


def revertir_zonas_viaticos(apps, schema_editor):
    ViaticosZonaTarifa = apps.get_model('anuncios', 'ViaticosZonaTarifa')
    ViaticosZonaTarifa.objects.filter(clave__in=['norte', 'centro', 'sur']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0048_requisicionesclasificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViaticosZonaTarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(choices=[('norte', 'Norte'), ('centro', 'Centro'), ('sur', 'Sur')], max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('hospedaje_noche', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('alimentacion_diaria', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('combustible_km', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarifa de Zona de Viaticos',
                'verbose_name_plural': 'Tarifas de Zonas de Viaticos',
                'db_table': 'viaticos_zona_tarifa',
                'ordering': ['clave'],
            },
        ),
        migrations.CreateModel(
            name='ViaticosPresupuestoDireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.PositiveIntegerField(default=portal.models._current_year)),
                ('monto_asignado', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('iddireccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos_viaticos', to='anuncios.personaldireccion')),
            ],
            options={
                'verbose_name': 'Presupuesto de Viaticos por Direccion',
                'verbose_name_plural': 'Presupuestos de Viaticos por Direccion',
                'db_table': 'viaticos_presupuesto_direccion',
                'ordering': ['-ejercicio', 'iddireccion__direccion'],
                'unique_together': {('iddireccion', 'ejercicio')},
            },
        ),
        migrations.CreateModel(
            name='ViaticosSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=30, unique=True)),
                ('motivo_comision', models.TextField()),
                ('origen', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('origen_latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('origen_longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destino_latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destino_longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('distancia_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('viaje_redondo', models.BooleanField(default=True)),
                ('dias', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('transporte', models.CharField(choices=[('vehiculo_interno', 'Vehiculo interno'), ('autobus', 'Autobus'), ('avion', 'Avion'), ('mixto', 'Mixto')], default='vehiculo_interno', max_length=20)),
                ('pasajes_estimados', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taxis_estimados', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('combustible_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hospedaje_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('alimentacion_estimada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estatus', models.CharField(choices=[('capturado', 'Capturado'), ('autorizado', 'Autorizado'), ('cancelado', 'Cancelado')], default='capturado', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viaticos_capturados', to=settings.AUTH_USER_MODEL)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_viaticos', to='anuncios.personaldireccion')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viaticos', to=settings.AUTH_USER_MODEL)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='anuncios.viaticospresupuestodireccion')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='anuncios.viaticoszonatarifa')),
            ],
            options={
                'verbose_name': 'Solicitud de Viaticos',
                'verbose_name_plural': 'Solicitudes de Viaticos',
                'db_table': 'viaticos_solicitud',
                'ordering': ['-fecha_creacion', '-id'],
            },
        ),
        migrations.RunPython(cargar_zonas_viaticos, reverse_code=revertir_zonas_viaticos),
    ]
