# Generated by Django 6.0.2 on 2026-04-08 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0049_viaticoszonatarifa_viaticospresupuestodireccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaticossolicitud',
            name='seguimiento_activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='viaticossolicitud',
            name='ultima_actualizacion_ubicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viaticossolicitud',
            name='ultima_latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='viaticossolicitud',
            name='ultima_longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='viaticossolicitud',
            name='ultima_precision_metros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='viaticossolicitud',
            name='ultima_velocidad_kmh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='ViaticosUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('precision_metros', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('velocidad_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fuente', models.CharField(choices=[('navegador', 'Navegador'), ('manual', 'Manual')], default='navegador', max_length=20)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones_viaticos', to=settings.AUTH_USER_MODEL)),
                ('viatico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='anuncios.viaticossolicitud')),
            ],
            options={
                'verbose_name': 'Ubicacion de Viaticos',
                'verbose_name_plural': 'Ubicaciones de Viaticos',
                'db_table': 'viaticos_ubicacion',
                'ordering': ['-fecha_reporte', '-id'],
            },
        ),
    ]
