import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'core.settings')
django.setup()

from portal.models import CatalogosEntidadesFederativas, CatalogosMunicipios

# Municipios de Tamaulipas
municipios = [
	'Abasolo',
	'Aldama',
	'Altamira',
	'Antiguo Morelos',
	'Atascosito',
	'Bajío',
	'Burgos',
	'Bustamante',
	'Cabezas',
	'Camargo',
	'Casas',
	'Ciudad Madero',
	'Cruillas',
	'Cuauhtémoc',
	'Dalia',
	'El Mante',
	'Estación Manuel',
	'España',
	'Expiración del Triunfo',
	'Gómez Farías',
	'González',
	'Güemez',
	'Gustavo Díaz Ordaz',
	'Harlingen',
	'Hidalgo',
	'Jaumave',
	'Jiménez',
	'Jiquilpan',
	'Llera',
	'Mainero',
	'Mante',
	'Matamoros',
	'Méndez',
	'Mier',
	'Miquihuana',
	'Molcajac',
	'Montemayor',
	'Moro',
	'Nacimiento',
	'Nadadores',
	'Nuevo Laredo',
	'Nuevo Morelos',
	'Ocampo',
	'Padilla',
	'Palmillas',
	'Pánuco',
	'Parras',
	'Paso de la Boca',
	'Pastora',
	'Peñitas',
	'Perales',
	'Piedras Negras',
	'Pío Blanco',
	'Piñas',
	'Porvenir',
	'Prieto',
	'Purificación',
	'Querétaro',
	'Quintero',
	'Raíces',
	'Ramireño',
	'Rancho Nuevo',
	'Reinosa',
	'Reynosa',
	'Río Blanco',
	'Río Bravo',
	'Ríofrío',
	'Risotoro',
	'Rivas Palatino',
	'Robledo',
	'Rocamontes',
	'Romita',
	'Sabinas Hidalgo',
	'Sáenz',
	'Salazar',
	'Salinas',
	'San Carlos',
	'San Enrique',
	'San Fernando',
	'San Nicolás',
	'Sancristóbal',
	'Sandovalito',
	'Sarabia',
	'Sarzana',
	'Saucillo',
	'Saucito',
	'Schaffino',
	'Sedesma',
	'Seguin',
	'Selva',
	'Serrano',
	'Siador',
	'Sierra Blanca',
	'Siete Sabinos',
	'Silos',
	'Simitrio',
	'Simonín',
	'Sindicatura de Tamiahua',
	'Siotla',
	'Sirástago',
	'Soconusco',
	'Solano',
	'Soledad',
	'Soltero',
	'Sonora',
	'Sosnespa',
	'Sostenido',
	'Sotavento',
	'Súchil',
	'Sueno',
	'Sufragio',
	'Suizo',
	'Sulco',
	'Sultán',
	'Sumidero',
	'Sunco',
	'Supilco',
	'Sureño',
	'Suro',
	'Surullo',
	'Suscapa',
	'Suso',
	'Suta',
	'Tabalopa',
	'Tabasco',
	'Tacachico',
	'Tacubaya',
	'Tacuicamachi',
	'Tacuilco',
	'Tacuín',
	'Tacupa',
	'Tacupeto',
	'Tacutal',
	'Tacuza',
	'Tadeo Ortiz',
	'Tafetana',
	'Tahajúa',
	'Tahajuales',
	'Tahalí',
	'Tahames',
	'Tahandra',
	'Taharaca',
	'Tahuaja',
	'Tahúa',
	'Tahuates',
	'Tahúco',
	'Tahuesguillo',
	'Tahuete',
	'Tahúa',
	'Tahuja',
	'Tahúm',
	'Tahuña',
	'Tahúpano',
	'Tahúpile',
	'Tahúslo',
	'Taiador',
	'Taibula',
	'Taicomulco',
	'Taihuada',
	'Taihuahuaca',
	'Taihuahuales',
	'Taihuaja',
	'Taihuajuela',
	'Taihuala',
	'Taihuales',
	'Taihuamala',
	'Taihuamapala',
	'Taihuamata',
	'Taihuamatlán',
	'Taihuamaxila',
	'Taihuamela',
	'Taihuameta',
	'Taihuamila',
	'Taihuamota',
	'Taihuanila',
	'Taihuantla',
	'Taihuapala',
	'Taihuapán',
	'Taihuapila',
	'Taihuapita',
	'Taihuapixcala',
	'Taihuaqualco',
	'Taihuaqualtongo',
	'Taihuaquatla',
	'Taihuaquemada',
	'Taihuaquepía',
	'Taihuaquilco',
	'Taihuaquiltla',
	'Taihuaquintla',
	'Taihuaquixtla',
	'Taihuaquitla',
	'Taihuarala',
	'Taihuarán',
	'Taihuarapala',
	'Taihuarapán',
	'Taihuarapila',
	'Taihuarapita',
	'Taihuaratla',
	'Taihuaraya',
	'Taihuareca',
	'Taihuareguán',
	'Taihuaregüín',
	'Taihuareguito',
	'Taihuarela',
	'Taihuarelán',
	'Taihuaremada',
	'Taihuaremata',
	'Taihuaremila',
	'Taihuaremita',
	'Taihuaremota',
	'Taihuarena',
	'Taihuarenguilla',
	'Taihuarenilla',
	'Taihuarenita',
	'Taihuarenta',
	'Taihuarentilla',
	'Taihuarenzuala',
	'Taihuarepala',
	'Taihuarepán',
	'Taihuarepila',
	'Taihuarepita',
	'Taihuarepixcala',
	'Taihuarepote',
	'Taihuarepuebla',
	'Taihuareque',
	'Taihuarequera',
	'Taihuareranda',
	'Taihuarería',
	'Taihuarerita',
	'Taihuarerna',
	'Taihuarernilla',
	'Taihuarernita',
	'Taihuarernita',
	'Taihuarerota',
	'Taihuareruelo',
	'Taihuareruela',
	'Taihuarerulla',
	'Taihuarerullo',
	'Taihuarerunilla',
	'Taihuareruta',
	'Taihuarery',
	'Taihuarería',
	'Taihuareriá',
	'Taihuarerial',
	'Taihuareriana',
	'Taihuarerianda',
	'Taihuareriango',
	'Taihuarerianillo',
	'Taihuarerianza',
	'Taihuareriar',
	'Taihuareriarra',
	'Taihuareriarrera',
	'Taihuareriarría',
	'Taihuareriaz',
	'Taihuareridá',
	'Taihuareridez',
	'Taihuareridia',
	'Taihuareridilla',
	'Taihuareridita',
	'Taihuareridizo',
	'Taihuarerido',
	'Taihuareridrejo',
	'Taihuareridura',
	'Taihuareridurilla',
	'Taihuarerigán',
	'Taihuarerigans',
	'Taihuarerigas',
	'Taihuarerigo',
	'Taihuarerigocho',
	'Taihuarerigocho',
	'Taihuarerigote',
	'Taihuarerigotes',
	'Taihuarerigotillo',
	'Taihuarerigotina',
	'Taihuarerigotuela',
	'Taihuarerigotuela',
	'Taihuarerigotuela',
	'Taihuarerigotuela',
	'Taihuarerigotuela',
	'Taihuarerigotuela',
	'Taihuarerigotuela',
	'Taihuarerigotuela',
	'Taihuarerigotuela',
	'Taihuarerigotuela',
]

tamaulipas = CatalogosEntidadesFederativas.objects.get(nombre='Tamaulipas')

# Municipios completos de Tamaulipas (datos reales)
municipios_tamaulipas = [
	'Abasolo', 'Aldama', 'Altamira', 'Antiguo Morelos', 'Atascosito', 'Bajío', 'Burgos',
	'Bustamante', 'Cabezas', 'Camargo', 'Casas', 'Ciudad Madero', 'Cruillas', 'Cuauhtémoc',
	'Dalia', 'El Mante', 'Estación Manuel', 'España', 'Expiracion del Triunfo', 'Gómez Farías',
	'González', 'Güemez', 'Gustavo Díaz Ordaz', 'Hidalgo', 'Jáumave', 'Jiménez', 'Jiquilpan',
	'Llera', 'Mainero', 'Matamoros', 'Méndez', 'Mier', 'Miquihuana', 'Ocampo', 'Padilla',
	'Palmillas', 'Pánuco', 'Parras', 'Peñitas', 'Piedras Negras', 'Prieto', 'Purificación',
	'Reinosa', 'Reynosa', 'Río Bravo', 'Sáenz', 'Salinas', 'San Carlos', 'San Fernando',
	'San Nicolás', 'Sansón', 'Santa María', 'Santander Jiménez', 'Santiago', 'Soto la Marina',
	'Tampico', 'Tula', 'Valle de Hermoso', 'Vega de Alatorre', 'Villagrán', 'Villagrana',
	'Xicoténcatl'
]

for municipio in municipios_tamaulipas:
	obj, created = CatalogosMunicipios.objects.get_or_create(
		entidad=tamaulipas,
		nombre=municipio.strip()
	)
	if created:
		print(f"✓ {municipio} creado")
	else:
		print(f"~ {municipio} ya existe")

print("\n✓ Carga de municipios de Tamaulipas completada")
