"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w3b^w=x4*b7s^kkfc7heo#z*8ef^vp)@*umim3oerbrc#eax#i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'portal.apps.PortalConfig',
]

AUTH_USER_MODEL = 'anuncios.PersonalEmpleados'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'portal.middleware.SessionTimeoutMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'portal' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'itavu',  # Cambia esto por el nombre real de tu base de datos
        'USER': 'postgres',   # Cambia esto por tu usuario de PostgreSQL
        'PASSWORD': 'r3O&V7c5iVQm.bD',    # Cambia esto por tu contraseña de PostgreSQL
        'HOST': 'localhost',
        'PORT': '5432',
        'DISABLE_SERVER_SIDE_CURSORS': True,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'portal' / 'static',
]

# Media files (Uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Contacto / reCAPTCHA
RECAPTCHA_SITE_KEY = os.getenv('RECAPTCHA_SITE_KEY', '')
RECAPTCHA_SECRET_KEY = os.getenv('RECAPTCHA_SECRET_KEY', '')
CONTACT_FORM_MIN_SECONDS = int(os.getenv('CONTACT_FORM_MIN_SECONDS', '3'))

# Configuración de sitio
SITE_URL = os.getenv('SITE_URL', 'http://localhost:8000')
CONTACT_FORM_RATE_LIMIT_SECONDS = int(os.getenv('CONTACT_FORM_RATE_LIMIT_SECONDS', '60'))
LOGIN_URL = '/login/'

# ===================== CONFIGURACIÓN DE SESIONES =====================
# Tiempo de vida de la sesión: 15 minutos por defecto (editable en configuracion_sistema)
SESSION_COOKIE_AGE = 15 * 60  # 900 segundos = 15 minutos (se actualiza desde ConfiguracionSistema)

# La sesión expira al cerrar el navegador: False = persiste después de cerrar
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Guardar la última actividad: permite mantener sesiones activas con actividad reciente
SESSION_SAVE_EVERY_REQUEST = True

# Usar cookies HTTPS solo en producción
SESSION_COOKIE_SECURE = False  # Cambiar a True en producción con HTTPS

# HttpOnly: la cookie no es accesible desde JavaScript
SESSION_COOKIE_HTTPONLY = True

# SameSite: previene ataques CSRF
SESSION_COOKIE_SAMESITE = 'Strict'
