# Generated by Django 6.0.2 on 2026-03-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0002_seguridadcontactanos'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguridadcontactanos',
            name='fecha_lectura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seguridadcontactanos',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
