# Generated by Django 6.0.2 on 2026-03-02 16:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0003_seguridadcontactanos_fecha_lectura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogosEntidadesFederativas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('clave', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'verbose_name': 'Entidad Federativa',
                'verbose_name_plural': 'Entidades Federativas',
                'db_table': 'catalogos_entidadesfederativas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='seguridadcontactanos',
            name='uuid_folio',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='CatalogosMunicipios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('clave', models.CharField(blank=True, max_length=3)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='anuncios.catalogosentidadesfederativas')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'catalogos_municipios',
                'ordering': ['entidad', 'nombre'],
                'unique_together': {('entidad', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='SeguridadConfiguracionDelSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255)),
                ('nombre_corto', models.CharField(max_length=100)),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('domicilio', models.CharField(max_length=255)),
                ('numero_exterior', models.CharField(max_length=20)),
                ('colonia', models.CharField(max_length=150)),
                ('codigo_postal', models.CharField(max_length=5)),
                ('smtp_host', models.CharField(blank=True, help_text='Ej: smtp.gmail.com', max_length=255)),
                ('smtp_puerto', models.IntegerField(default=587, help_text='Puerto SMTP (587 para TLS, 465 para SSL)')),
                ('smtp_usuario', models.CharField(blank=True, max_length=255)),
                ('smtp_contrasena', models.CharField(blank=True, max_length=255)),
                ('smtp_usar_tls', models.BooleanField(default=True)),
                ('smtp_usar_ssl', models.BooleanField(default=False)),
                ('correo_remitente', models.EmailField(blank=True, help_text='Correo desde el que se enviarán notificaciones', max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_municipio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anuncios.catalogosmunicipios')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
                'db_table': 'seguridad_configuraciondelsistema',
            },
        ),
    ]
