# Generated by Django 6.0.2 on 2026-03-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0005_catalogosdelegaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDireccion',
            fields=[
                ('iddireccion', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(help_text='Nombre de la dirección', max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional de la dirección')),
                ('activo', models.BooleanField(default=True, help_text='Indica si la dirección está vigente')),
                ('fecha_captura', models.DateTimeField(auto_now_add=True, help_text='Fecha cuando se registró la dirección')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha de la última modificación')),
                ('usuario_captura', models.CharField(blank=True, help_text='Usuario que capturó el registro', max_length=100)),
                ('usuario_modificacion', models.CharField(blank=True, help_text='Usuario que modificó el registro', max_length=100)),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'db_table': 'personal_direccion',
                'ordering': ['direccion'],
            },
        ),
    ]
