# Generated by Django 6.0.2 on 2026-03-03 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0007_personaldepartamento'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalEmpleados',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(help_text='Nombre de usuario para login', max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('curp', models.CharField(blank=True, max_length=18, unique=True)),
                ('rfc', models.CharField(blank=True, max_length=13, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('domicilio', models.TextField(blank=True)),
                ('puesto', models.CharField(blank=True, max_length=200)),
                ('numero_empleado', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('tipo_contrato', models.CharField(blank=True, choices=[('Definitivo', 'Definitivo'), ('Temporal', 'Temporal'), ('Honorarios', 'Honorarios')], max_length=50)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('recordar_dispositivo', models.BooleanField(default=False, help_text='Permite recordar este dispositivo')),
                ('token_dispositivo', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_ultimo_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='personal_empleados_groups', to='auth.group')),
                ('iddepartamento', models.ForeignKey(blank=True, help_text='Departamento del empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='anuncios.personaldepartamento')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='personal_empleados_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'personal_empleados',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='RecuperacionContrasena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('utilizado', models.BooleanField(default=False)),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recuperaciones', to='anuncios.personalempleados')),
            ],
            options={
                'verbose_name': 'Recuperación de Contraseña',
                'verbose_name_plural': 'Recuperaciones de Contraseña',
                'db_table': 'recuperacion_contrasena',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
