# Generated by Django 6.0.2 on 2026-03-03 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0014_personalempleados_nombre_dividido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalpuestos',
            options={'ordering': ['nombre'], 'verbose_name': 'Puesto', 'verbose_name_plural': 'Puestos'},
        ),
        migrations.AlterModelOptions(
            name='personaltipodecontratacion',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de Contratación', 'verbose_name_plural': 'Tipos de Contratación'},
        ),
    ]
