# Generated by Django 6.0.2 on 2026-03-03 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0015_alter_personalpuestos_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(help_text='Razón social de la empresa', max_length=255)),
                ('nombre_corto', models.CharField(help_text='Nombre corto de la empresa (ej: ITAVU)', max_length=50)),
                ('rfc', models.CharField(help_text='RFC de la empresa', max_length=13, unique=True)),
                ('domicilio', models.TextField(help_text='Domicilio de la empresa')),
                ('smtp_host', models.CharField(blank=True, help_text='Servidor SMTP (ej: smtp.gmail.com)', max_length=255)),
                ('smtp_port', models.IntegerField(default=587, help_text='Puerto SMTP (ej: 587)')),
                ('smtp_usuario', models.CharField(blank=True, help_text='Usuario SMTP', max_length=255)),
                ('smtp_contrasena', models.CharField(blank=True, help_text='Contraseña SMTP', max_length=255)),
                ('smtp_usar_tls', models.BooleanField(default=True, help_text='Usar TLS en SMTP')),
                ('email_desde', models.EmailField(help_text='Email desde el cual se enviarán los correos', max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('sitio_web', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sistema/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
                'db_table': 'configuracion_sistema',
            },
        ),
        migrations.CreateModel(
            name='UsuariosDelSistema',
            fields=[
                ('id_usuario_sistema', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(help_text='Nombre de usuario para login', max_length=100, unique=True)),
                ('correo', models.EmailField(help_text='Correo electrónico', max_length=254, unique=True)),
                ('contrasena', models.CharField(help_text='Contraseña encriptada', max_length=255)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('empleado', 'Empleado'), ('viewer', 'Visualizador')], default='empleado', help_text='Rol del usuario', max_length=20)),
                ('activo', models.BooleanField(default=True, help_text='¿El usuario está activo?')),
                ('requiere_cambio_contrasena', models.BooleanField(default=True, help_text='¿Requiere cambiar contraseña?')),
                ('fecha_ultimo_login', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(help_text='Usuario que creó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_creados', to=settings.AUTH_USER_MODEL)),
                ('id_empleado', models.OneToOneField(help_text='Empleado asociado', on_delete=django.db.models.deletion.CASCADE, related_name='usuario_sistema', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario del Sistema',
                'verbose_name_plural': 'Usuarios del Sistema',
                'db_table': 'usuarios_del_sistema',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
