# Generated by Django 6.0.1 on 2026-03-06 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0019_patrimonio_modelos'),
        ('anuncios', '0018_colacorreos'),
    ]

    operations = [
    ]
