# Generated by Django 6.0.1 on 2026-03-06 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0022_renombrar_tabla_patrimonio_bienes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatrimonioResguardo',
            fields=[
                ('idresguardo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField(help_text='Fecha de asignación del bien')),
                ('fecha_devolucion', models.DateField(blank=True, help_text='Fecha de devolución del bien', null=True)),
                ('observaciones_asignacion', models.TextField(blank=True, help_text='Observaciones al momento de asignar')),
                ('observaciones_devolucion', models.TextField(blank=True, help_text='Observaciones al momento de devolver')),
                ('activo', models.BooleanField(default=True, help_text='¿Es el resguardo actual?')),
                ('usuario_asignacion', models.CharField(blank=True, help_text='Usuario que realizó la asignación', max_length=100)),
                ('usuario_devolucion', models.CharField(blank=True, help_text='Usuario que registró la devolución', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('bien', models.ForeignKey(help_text='Bien resguardado', on_delete=django.db.models.deletion.CASCADE, related_name='resguardos', to='anuncios.patrimoniobienesdelinstituto')),
                ('empleado', models.ForeignKey(help_text='Empleado responsable', on_delete=django.db.models.deletion.PROTECT, related_name='resguardos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resguardo de Bien',
                'verbose_name_plural': 'Resguardos de Bienes',
                'db_table': 'patrimonio_resguardos',
                'ordering': ['-fecha_asignacion'],
                'indexes': [models.Index(fields=['bien', 'activo'], name='patrimonio__bien_id_c60219_idx'), models.Index(fields=['empleado', 'activo'], name='patrimonio__emplead_eae1cc_idx'), models.Index(fields=['fecha_asignacion'], name='patrimonio__fecha_a_beded1_idx')],
            },
        ),
    ]
