# Generated by Django 6.0.1 on 2026-03-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0024_agregar_campos_oficio_resguardo'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrimoniobienesdelinstituto',
            name='archivo_factura',
            field=models.FileField(blank=True, help_text='Archivo PDF de la factura', null=True, upload_to='patrimonio/facturas/'),
        ),
    ]
