# Generated by Django 6.0.2 on 2026-03-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0026_patrimonioentregadepartamento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personaldepartamento',
            options={'ordering': ['iddireccion__ordenjerarquia', 'ordenjerarquia', 'departamento'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='personaldireccion',
            options={'ordering': ['ordenjerarquia', 'direccion'], 'verbose_name': 'Dirección', 'verbose_name_plural': 'Direcciones'},
        ),
        migrations.AddField(
            model_name='personaldepartamento',
            name='ordenjerarquia',
            field=models.IntegerField(default=0, help_text='Orden jerárquico para el departamento'),
        ),
        migrations.AddField(
            model_name='personaldireccion',
            name='ordenjerarquia',
            field=models.IntegerField(default=0, help_text='Orden jerárquico para la dirección'),
        ),
    ]
