# Generated by Django 6.0.1 on 2026-03-10 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0028_alter_patrimonioproveedor_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='duracion_intro_segundos',
            field=models.IntegerField(default=3, help_text='Duración de la pantalla de introducción en segundos (1-6)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
