# Generated by Django 6.0.1 on 2026-03-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0029_configuracionsistema_duracion_intro_segundos'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogosmarcas',
            name='categoria',
            field=models.CharField(choices=[('informatica', 'Informática'), ('oficina', 'Oficina'), ('electrica', 'Eléctrica'), ('telecomunicaciones', 'Telecomunicaciones'), ('vehicular', 'Vehicular'), ('muebles', 'Muebles'), ('construccion', 'Construcción'), ('otro', 'Otro')], default='otro', help_text='Categoría de la marca', max_length=50),
        ),
    ]
