# Generated by Django 6.0.1 on 2026-03-10 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0033_patrimonioestatusdelregistro'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrimoniobienesdelinstituto',
            name='baja_fecha',
            field=models.DateField(blank=True, help_text='Fecha de baja del bien', null=True),
        ),
        migrations.AddField(
            model_name='patrimoniobienesdelinstituto',
            name='baja_oficio',
            field=models.FileField(blank=True, help_text='Archivo PDF del oficio de baja', null=True, upload_to='patrimonio/bajas/'),
        ),
        migrations.AddField(
            model_name='patrimoniobienesdelinstituto',
            name='estatus_registro',
            field=models.ForeignKey(blank=True, help_text='Estatus del registro en el patrimonio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='anuncios.patrimonioestatusdelregistro'),
        ),
    ]
