# Generated by Django 6.0.1 on 2026-03-10 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0034_patrimoniobienesdelinstituto_baja_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='patrimoniobienesdelinstituto',
            name='patrimonio__activo_ccd21a_idx',
        ),
        migrations.AddField(
            model_name='patrimoniobienesdelinstituto',
            name='idestatus',
            field=models.ForeignKey(blank=True, default=1, help_text='Estatus del registro en el patrimonio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='anuncios.patrimonioestatusdelregistro'),
        ),
        migrations.AddIndex(
            model_name='patrimoniobienesdelinstituto',
            index=models.Index(fields=['idestatus'], name='patrimonio__idestat_dbff16_idx'),
        ),
        migrations.RemoveField(
            model_name='patrimoniobienesdelinstituto',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='patrimoniobienesdelinstituto',
            name='estatus_registro',
        ),
    ]
