# Generated by Django 6.0.1 on 2026-03-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0036_patrimoniobienesdelinstituto_baja_numero_oficio'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrimoniobienesdelinstituto',
            name='numinv_monitor',
            field=models.CharField(blank=True, help_text='Número de inventario del monitor emparejado', max_length=50),
        ),
        migrations.AddField(
            model_name='patrimoniobienesdelinstituto',
            name='numserie_monitor',
            field=models.CharField(blank=True, help_text='Número de serie del monitor emparejado', max_length=50),
        ),
        migrations.AddField(
            model_name='patrimoniobienesdelinstituto',
            name='tipo_equipo',
            field=models.CharField(choices=[('computadora', 'Computadora/PC'), ('otro', 'Otro')], default='otro', help_text='Tipo de equipo (para campos de monitor)', max_length=20),
        ),
    ]
